"""update schema

Revision ID: 43b424abe644
Revises: 6fca42c0a8fd
Create Date: 2026-04-22 16:08:18.725461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b424abe644'
down_revision: Union[str, Sequence[str], None] = '6fca42c0a8fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_tbl', sa.Column('name', sa.Text(), nullable=True))
    op.add_column('postings_tbl', sa.Column('board_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('postings_tbl', 'board_id')
    op.drop_column('company_tbl', 'name')
    # ### end Alembic commands ###
