"""update schema

Revision ID: 6fca42c0a8fd
Revises: d7508ab66e9c
Create Date: 2026-04-21 23:07:14.595109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fca42c0a8fd'
down_revision: Union[str, Sequence[str], None] = 'd7508ab66e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postings_tbl', sa.Column('scrapeStatus', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('postings_tbl', 'scrapeStatus')
    # ### end Alembic commands ###
