"""Link user with posting, add external user id for authentication

Revision ID: 7978da17cefb
Revises: ecefbfc17630
Create Date: 2026-04-20 19:33:33.034508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7978da17cefb'
down_revision: Union[str, Sequence[str], None] = 'ecefbfc17630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postings_tbl', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'postings_tbl', 'user_tbl', ['user_id'], ['user_id'])
    op.add_column('user_tbl', sa.Column('user_external_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tbl', 'user_external_id')
    op.drop_constraint(None, 'postings_tbl', type_='foreignkey')
    op.drop_column('postings_tbl', 'user_id')
    # ### end Alembic commands ###
