"""add source column to postings

Revision ID: 8abfe2aa9ae7
Revises: be5aeb9439aa
Create Date: 2026-04-25 19:19:44.872200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8abfe2aa9ae7'
down_revision: Union[str, Sequence[str], None] = 'be5aeb9439aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postings_tbl', sa.Column('source', sa.Text(), server_default=sa.text("'auto'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('postings_tbl', 'source')
    # ### end Alembic commands ###
