"""add search configs table

Revision ID: be5aeb9439aa
Revises: a1c2e3f4b5d6
Create Date: 2026-04-25 16:23:58.067579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be5aeb9439aa'
down_revision: Union[str, Sequence[str], None] = 'a1c2e3f4b5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_configs_tbl',
    sa.Column('search_config_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('board', sa.Text(), nullable=False),
    sa.Column('params', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), nullable=False),
    sa.Column('results_wanted', sa.Integer(), server_default=sa.text('25'), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'Idle'"), nullable=False),
    sa.Column('total_scraped', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_tbl.user_id'], ),
    sa.PrimaryKeyConstraint('search_config_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_configs_tbl')
    # ### end Alembic commands ###
