"""update schema

Revision ID: d7508ab66e9c
Revises: 7978da17cefb
Create Date: 2026-04-20 21:19:28.844358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7508ab66e9c'
down_revision: Union[str, Sequence[str], None] = '7978da17cefb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_template_tbl', sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.add_column('resume_template_tbl', sa.Column('name', sa.Text(), nullable=True))
    op.drop_column('resume_template_tbl', '_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_template_tbl', sa.Column('_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False))
    op.drop_column('resume_template_tbl', 'name')
    op.drop_column('resume_template_tbl', 'id')
    # ### end Alembic commands ###
