/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResumeTemplatesRouteImport } from './routes/resume-templates'
import { Route as ResumeBuilderRouteImport } from './routes/resume-builder'
import { Route as JobSearchRouteImport } from './routes/job-search'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeTemplatesRoute = ResumeTemplatesRouteImport.update({
  id: '/resume-templates',
  path: '/resume-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeBuilderRoute = ResumeBuilderRouteImport.update({
  id: '/resume-builder',
  path: '/resume-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const JobSearchRoute = JobSearchRouteImport.update({
  id: '/job-search',
  path: '/job-search',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/job-search': typeof JobSearchRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/resume-templates': typeof ResumeTemplatesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/job-search': typeof JobSearchRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/resume-templates': typeof ResumeTemplatesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/job-search': typeof JobSearchRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/resume-templates': typeof ResumeTemplatesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/job-search'
    | '/resume-builder'
    | '/resume-templates'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/job-search'
    | '/resume-builder'
    | '/resume-templates'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/job-search'
    | '/resume-builder'
    | '/resume-templates'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  JobSearchRoute: typeof JobSearchRoute
  ResumeBuilderRoute: typeof ResumeBuilderRoute
  ResumeTemplatesRoute: typeof ResumeTemplatesRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-templates': {
      id: '/resume-templates'
      path: '/resume-templates'
      fullPath: '/resume-templates'
      preLoaderRoute: typeof ResumeTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-builder': {
      id: '/resume-builder'
      path: '/resume-builder'
      fullPath: '/resume-builder'
      preLoaderRoute: typeof ResumeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-search': {
      id: '/job-search'
      path: '/job-search'
      fullPath: '/job-search'
      preLoaderRoute: typeof JobSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  JobSearchRoute: JobSearchRoute,
  ResumeBuilderRoute: ResumeBuilderRoute,
  ResumeTemplatesRoute: ResumeTemplatesRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
